### ISSUE TITLE
Crash on API level 23

### ISSUE THREAD

**Issue by revolutionair** [Azure-Samples/ms-identity-android-java#16]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Try to run the app on a device running on API level 23 or lower

### Any log messages given by the failure
Binary XML file line #16: Error inflating class android.support.design.widget.NavigationView

### Expected/desired behavior
Expected: the app doesn't crash. Actual: the app crashes

### OS and Version?
N/A

### Versions
1

### Mention any other details that might be useful
The crash is caused by the ImageView in the navigation drawer header. The image that is set as source to that ImageView in nav_header_main.xml is microsoft_logo.png. This png file is placed in the drawable-v24 folder, so it won't be used on API levels lower than 24. My fix: move the file from drawable-v24 folder to the drawable folder.

**Comment by rpdome** [comment]
Thanks for reporting @revolutionair! I've submitted a PR for this issue.
