### ISSUE TITLE
authenticated or no? no certificates found AND you cannot access this right now

### ISSUE THREAD

**Issue by jfitz1** [Azure-Samples/ms-identity-android-java#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run library in Android studio
sign in
  

### Any log messages given by the failure
>

### Expected/desired behavior
>
able to login

### OS and Version?
> Android 9, Samsung S8
### Versions
> Knox 3.2.1
> Android Security patch level October 1, 2019

### Mention any other details that might be useful

![screenshot-a2](https://user-images.githubusercontent.com/17125886/70479302-10189e00-1aab-11ea-98e0-453df514bc68.png)

![screenshot-b](https://user-images.githubusercontent.com/17125886/70479329-1d358d00-1aab-11ea-9673-9b694b0b22b7.png)

![screenshot-c](https://user-images.githubusercontent.com/17125886/70479353-26bef500-1aab-11ea-8ccc-d6b5f1358e9b.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by FrankBrullo** [comment]
+1 I have the same issue. Please, someone should fix it.

**Comment by shoatman** [comment]
This looks like you're hitting a conditional access policy requiring an enrolled and/or managed device.  Do you have the Intune Company Portal and/or the Microsoft Authenticator app installed?  If so, you can install the device certificate to the default browser on the device.  From within Settings in either app look for "Enable browser access" and select it.  For Authenticator it's inside the "Device registration" section.

**Comment by jfitz1** [comment]
I really appreciate the help, thank you!

Did not have either Intune Company Portal and/or the Microsoft Authenticator app installed.  I am vendor working on a product to integrate into Azure AD for a client.  I think the client is using different software to register devices and mutual factor authentication.  

Installed Microsoft Authenticator app and could not login with Azure AD credentials. 
Installed Intune Company Portal app and got a similar response as original issue.  Screenshot from Intune Company Portal app below.  

![Screenshot_20191210-115401_Company_Portal](https://user-images.githubusercontent.com/17125886/70551052-cbd9dc00-1b44-11ea-948f-2e7746dbb3f6.png)

**Comment by rpdome** [comment]
This seems to be a configuration issue. Are you the admin by any chance?

If not, I'd suggest working with the admin and check if there is any [conditional access policy](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-policies) that are set in order to access this, or any resources.

You can access the conditional policy page [here](https://portal.azure.com/#blade/Microsoft_AAD_IAM/ConditionalAccessBlade/Policies)
