### ISSUE TITLE
How to call performOperationOnSignOut method or pass mSingleAccountApp  from another class in Android kotlin

### ISSUE THREAD

**Issue by sachin07** [Azure-Samples/ms-identity-android-java#20]
I want to call the below method from another class: 

    fun performOperationOnSignOut() {
        val signOutText = "Signed Out."
    
        mSingleAccountApp!!.signOut(object : ISingleAccountPublicClientApplication.SignOutCallback {
            override fun onSignOut() {

                Toast.makeText(applicationContext, signOutText, Toast.LENGTH_SHORT)
                    .show()

            }

            override fun onError(exception: MsalException) {
                //displayError(exception)
            }
        })

    }

How can i achieve the same 

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rpdome** [comment]
Hi @sachin07 , could you please give us a more concrete example of what you're trying to achieve? 

Thanks,
Dome
