### ISSUE TITLE
unclear how to activate broker usage

### ISSUE THREAD

**Issue by roelofk** [Azure-Samples/ms-identity-android-java#30]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
 - Build the app with single user mode configuration
- Make sure Microsoft Authenticator is installed on your device
- Click sign in and see that it is not opening the broker (Microsoft Authenticator) to select your account

### Any log messages given by the failure
>

### Expected/desired behavior
> On sign in opening the broker 

### OS and Version?
> Android Samsung Galaxy S7 running Android 8.0.0

### Versions
>

### Mention any other details that might be useful
Might be that I'm overlooking some configuration, but i can't find it anywhere. Please let me know.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hamiltonha** [comment]
The sample app should work with the broker without any additional changes being made to the configuration. Did you change anything else in the sample app?

**Comment by roelofk** [comment]
> The sample app should work with the broker without any additional changes being made to the configuration. Did you change anything else in the sample app?

I have now tried:
1. Different devices (Samsung Galaxy S8, Samsung Galaxy S7) with Android 8.0.0 - Ms Authenticator does not open, I get relayed to the Microsoft web page to log in
2. Running the example app with my settings for the JSON auth_config_single_account and the correct settings in the Android manifest host and path - Ms Authenticator does not open, I get relayed to the Microsoft web page to log in
3. Running the example unmodified - - Ms Authenticator does not open, I get relayed to the Microsoft web page to log in

I checked to see if I got the latest Authenticator installed, which is the case.

**Comment by rpdome** [comment]
Can you clarify on the "Ms Authenticator does not open" part? Are you expecting an account picker page inside Authenticator? 

If you just freshly uninstall authenticator, and you don't have any available accounts (the is not the same as the MFA account you added through Authenticator), then you will still see the microsoft log in webpage even in Broker flow.

**Comment by roelofk** [comment]
Well when i use the ADAL library i see the broker (MS Authenticator) as shown in the first screenshot. 
In the second screenshot you see te screen that is shown when I use MSAL (I don't think it's the broker, or am i wrong???)

Screenshot with use of ADAL (this has the broker)
![Screenshot_20200224-144045_Authenticator](https://user-images.githubusercontent.com/5304721/75253132-3f9f9280-57de-11ea-8fa1-4baf5267cb70.jpg)
Screenshot with use of MSAL (seems like it is not opening the broker):
![Screenshot_20200224-144438_Authenticator](https://user-images.githubusercontent.com/5304721/75253156-48906400-57de-11ea-9e9f-4113d3839610.jpg)

**Comment by roelofk** [comment]
Is there anyone who can help here?? or at least try it out on their end???

**Comment by rpdome** [comment]
We've tested your scenario (with both internal debug builds and production builds) and are unable to reproduce the issue.

You will only see the account picker (first picture) only when.
1. There is at least one account that was signed in through Broker before.
2. Login hint is not provided.

Otherwise, the broker will display the login page. (What happened here is that the account picker will just proceed with the "Add account" option in the account picker for you).

There is a few thing that I'd like to you check
1. Make sure you're using the latest commit of **unmodified** sample app.
2. in your json file, make sure that **broker_redirect_uri_registered** is set to **true**.

**Comment by roelofk** [comment]
@rpdome this morning I got an update of the Microsoft Authenticator through the Google playstore and now it seems to be working.
So version 6.2002.0898 seemed to be broken and the new version 6.2002.1200 fixed the problem. Thank you for helping out.
