### ISSUE TITLE
Unable to get this sample to work because of version issues when compiling

### ISSUE THREAD

**Issue by RayGHeld** [Azure-Samples/ms-identity-android-java#73]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Download sample and upgrade modules ( Android studio will be prompting you to upgrade ).

### Any log messages given by the failure
>
2 issues were found when checking AAR metadata:

  1.  Dependency 'androidx.datastore:datastore-preferences:1.0.0' requires libraries and applications that
      depend on it to compile against version 30 or later of the
      Android APIs.

      :app is currently compiled against android-28.

      Recommended action: Update this project to use a newer compileSdk
      of at least 30, for example 33.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

  2.  Dependency 'androidx.datastore:datastore:1.0.0' requires libraries and applications that
      depend on it to compile against version 30 or later of the
      Android APIs.

      :app is currently compiled against android-28.

      Recommended action: Update this project to use a newer compileSdk
      of at least 30, for example 33.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

### Expected/desired behavior
> Sample should build with the upgrades as being required by android studio

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> Windows 11

### Mention any other details that might be useful

I have tried upgrading both Gradle and Maven.  I have uninstalled android studio, removed both gradle and Maven and started all over.  I still get these errors.  Anything I do based on stack-overflows to resolve this issue, only makes it worse. 

![image](https://github.com/Azure-Samples/ms-identity-android-java/assets/40300226/0dd9c785-97cf-4cce-8281-22bdf98b3da2)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RayGHeld** [comment]
I will also mention that a team member also downloaded the sample, followed the instructions and is having the same problem.

**Comment by tanmaymanolkar1** [comment]
Provided the update :

Changes recently to bump the compilesdk to 34 version and targetsdk to 33 version

Could you give it another try, we believe this should help solve the problem.

https://github.com/Azure-Samples/ms-identity-android-java/pull/72
